# Required
version: 2

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  builder: html
  configuration: documentation/source/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
# formats:
#    - pdf
#    - epub

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - pip install sphinx sphinx-autodoc-typehints
    - export PYTHONPATH=$PYTHONPATH:$(pwd)
    - sphinx-quickstart
    - sphinx-apidoc -o documentation/source/ bio_compose
    - sphinx-build -b html documentation/source/ $READTHEDOCS_OUTPUT/html